apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: prwlxh2ts-dotnet-basic 
  janus-idp.io/tekton: prwlxh2ts-dotnet-basic
  backstage.io/kubernetes-id: prwlxh2ts-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: prwlxh2ts-dotnet-basic
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml